# update || true
# upgrade || true
# 
cask_args appdir: '/# Applications'
# 
# tap 'caskroom/cask'
# tap 'homebrew/bundle'
# 
brew 'ack'
# brew 'coreutils'
# brew 'go'
# brew 'grc'
# brew 'imagemagick'
# brew 'jp2a'
# brew 'libcaca', args: ['with-# imlib2']
# brew 'libgit2'
# brew 'openssl'
# brew 'node'
# brew 'readline'
brew 'postgresql'
# brew 'ruby-build'
# brew 'rbenv'
# brew 'roundup'
# brew 'spaceman-diff'
# brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
 
# cask '1password'
# cask 'adium'
# cask 'atom'
cask 'firefox'
# cask 'garmin-express'
cask 'google-chrome'
cask 'handbrake'
cask 'hipchat'
cask 'iterm2'
cask 'pgadmin3'
cask 'spotify'
cask 'steam'
cask 'transmission'
cask 'virtualbox'
# cask 'vlc'
# 